<?php
class Test_TestCtrl extends Apps_Programs_Kernel
{
/***************************************************************/
    /**
     * Default method
     * 
     * @return void
     */
    public function preInit()
    {
        $this->meta->title('Guest Book');
        $this->meta->description('Basic guest book; generated by DadiWeb');
        $this->meta->keywords('basic, guest, book, generated, by, dadiweb');
        parent::preInit();
    }
    
/***************************************************************/
    /**
     * Index method.
     * 
     * @return void
     */
    public function IndexMethod(){
        $this->rendered->ajax=false;
        $form=new Test_Forms_Add(array('strings'=>$this->strings));
        $form=new Test_Forms_Add(array('strings'=>$this->strings));
        $t=new Test_Db_Guestbook();
        if($this->request->isXHR()){
            $this->rendered->ajax=true;
            $this->layout->useRendered(false);
            if($this->request->isPost()){
                if($form->isValid($this->response->getPost())){
                    $array['result'] = 'OK';
                }else{
                    
                    $array['result'] = 'ERROR';
                }
                $form->setValue('captcha','');
                $array['html'] = str_replace('&quot;', '\"', $this->layout->getActionView());
                $this->response->setBody(json_encode($array))->sendResponse();
            }
        }
    }
    
/***************************************************************/
}